<div align="center">

**LAPORAN PRAKTIKUM**

**ALGORITMA DAN PEMOGRAMAN**

**“Tipe Data dan Variabel”**

**Disusun Oleh :**

**Raldo Restanggi Alfarizy**

**2611533018**

**Dosen Pengampu:**

**Dr. Wahyudi, S.T, .M.T**

**Asisten Praktikum:**

**Sherly Sukmadira**

<br>

 <img src="images/logo_unand.png" width="200">

<br>

**FAKULTAS TEKNOLOGI INFORMASI**

**DEPARTEMEN INFORMATIKA**

**UNIVERSITAS ANDALAS**

**2026**

</div>

## KATA PENGANTAR

Puji beserta syukur saya panjatkan atas kehadirat Tuhan Yang Maha Esa yang telah memberikan rahmat dan berkatnya, sehingga saya dapat menyelesaikan laporan praktikum mengenai pengenalan tipe data dan variabel Python yang telah dilaksanakan sebagai pertemuan ke-2 untuk mata kuliah Praktikum Algoritma dan Pemrograman. Praktikum ini berfokus pada pembahasan jenis - jenis tipe data yang ada pada bahasa pemrograman Python.

Melalui praktikum ini, hasil yang diharapkan adalah saya dapat memahami secara langsung konsep mengenai macam - macam tipe data Python dan bisa mengindentifikasi nilai dari suatu variabel serta bisa mengelompokkan nilai variabel berdasarkan tipe datanya pada bahasa pemrograman Python.

Saya menyadari bahwa laporan praktikum ini masih memiliki banyak kekurangan. Oleh karena itu, kritik dan saran yang membangun sangat diharapkan demi perbaikan dan pengembangan di masa mendatang.

Padang, 10 September 2026

---
# BAB I
# PENDAHULUAN

## 1.1 Latar Belakang
Perkembangan teknologi informasi membuat pengolahan data dan pembuatan sistem menjadi semakin dibutuhkan dalam berbagai bidang. Salah satu bahasa pemrograman yang banyak digunakan untuk hal tersebut adalah Python. Python cukup mudah dipelajari karena memiliki sintaks yang sederhana. Selain itu, Python juga dapat digunakan untuk berbagai keperluan, seperti membuat aplikasi, mengolah data, dan mengembangkan kecerdasan buatan. Karena itu, memahami dasar-dasar Python menjadi langkah awal dalam mempelajari pemrograman.

Salah satu dasar yang perlu dipahami adalah variabel. Variabel berfungsi sebagai tempat untuk menyimpan nilai yang nantinya dapat digunakan kembali ketika program dijalankan. Dengan adanya variabel, data yang digunakan dalam program dapat disimpan dan diolah dengan lebih mudah.

Tipe data juga menjadi bagian penting dalam pemrograman Python. Tipe data menunjukkan jenis nilai yang digunakan, misalnya int untuk bilangan bulat, float untuk bilangan desimal, str untuk teks, dan bool untuk nilai benar atau salah. Python menggunakan sistem dynamic typing, sehingga tipe data akan dikenali secara otomatis sesuai dengan nilai yang diberikan pada variabel.

Variabel dan tipe data merupakan materi dasar yang perlu dikuasai sebelum mempelajari pemrograman lebih lanjut. Melalui praktikum ini, praktikan diharapkan dapat memahami cara menggunakan variabel, mengenali beberapa tipe data dasar, dan menerapkannya dalam program sederhana menggunakan Python.

## 1.2 Tujuan
1. Memahami Konsep Dasar Variabel.
2. Mengenali Jenis Tipe Data Variabel.
3. Mengimplementasikan Deklarasi dan Konversi Tipe Data.

## 1.3 Manfaat
1. Penguasaan Fondasi Pemrograman
2. Peningkatan Keterampilan Praktis (Hands-On)
3. Pencegahan Kesalahan Logika Kode

---
# BAB II
# PEMBAHASAN

## 2.1 Landasan Teori

**1. Pengenalan Bahasa Pemrograman Python**

Python merupakan salah satu bahasa pemrograman tingkat tinggi yang menggunakan konsep interpreted, object-oriented, dan dynamically typed. Python pertama kali dikembangkan oleh Guido van Rossum pada tahun 1991. Bahasa ini dirancang dengan sintaks yang sederhana dan mudah dibaca, sehingga cukup banyak digunakan untuk pembelajaran maupun pengembangan program. Python dapat diterapkan dalam berbagai bidang, seperti pembuatan perangkat lunak, otomatisasi, analisis data, dan kecerdasan buatan.

​**2. Konsep Variabel dalam Python**

Variabel digunakan untuk menyimpan sebuah nilai yang nantinya dapat digunakan kembali dalam program. Pada Python, variabel dapat dibuat secara langsung dengan memberikan nilai menggunakan tanda = tanpa harus menentukan tipe datanya terlebih dahulu. Dalam penulisannya, nama variabel memiliki beberapa aturan, seperti membedakan huruf besar dan kecil (case-sensitive), tidak boleh diawali angka, serta tidak dapat menggunakan kata kunci yang sudah digunakan oleh Python.

**​3. Tipe Data Dasar**

Tipe data menunjukkan jenis nilai yang disimpan dalam sebuah variabel. Python memiliki beberapa tipe data dasar yang sering digunakan, yaitu:

- Integer (int): digunakan untuk menyimpan bilangan bulat, seperti -5, 0, dan 100.

- Float (float): digunakan untuk menyimpan bilangan yang memiliki nilai desimal, seperti 3.14 dan -0.01.

- String (str): digunakan untuk menyimpan teks atau kumpulan karakter yang ditulis menggunakan tanda petik, seperti "Praktikum Python".

- Boolean (bool): digunakan untuk menyimpan nilai logika yang terdiri dari True dan False.

**​4. Dynamic Typing dan Type Casting**

Python menggunakan sistem dynamic typing, yaitu tipe data variabel dapat ditentukan secara otomatis berdasarkan nilai yang diberikan ketika program dijalankan. Python juga menyediakan type casting yang digunakan untuk mengubah suatu nilai dari satu tipe data ke tipe lainnya. Contohnya adalah penggunaan int(), float(), dan str(). Pemahaman mengenai type casting diperlukan agar data dapat digunakan sesuai dengan operasi yang dilakukan dan mengurangi kemungkinan terjadinya type error.

## 2.2 Kode Program

### 2.2.1 Program "Boolean_2611533018"

In [2]:
# Buat file dengan nama Boolean_NIM.py
# Nama variabel ditambah 4 digit terakhir NIM contoh : a_3018
# Deklarasi variabel dengan tipe data boolean
is_lulus_3018 = True
is_cumlaude_3018 = True

# Mengunakan Boolean
nilai_3018 = 85
batas_lulus_3018 = 75

# Menentukan nilai Boolean dari kondisi
status_kelulusan_3018 = nilai_3018 >= batas_lulus_3018 # Hasilnya akan True

print("=== Check kelulusan ===")
print("Nilai : ", nilai_3018)
print("Apakah lulus? : ", status_kelulusan_3018)
if is_lulus_3018 and is_cumlaude_3018:
    print("Selamat, Anda lulus dengan predikat Cumlaude!")

=== Check kelulusan ===
Nilai :  85
Apakah lulus? :  True
Selamat, Anda lulus dengan predikat Cumlaude!


**Penjelasan :** Program ini mendemonstrasikan tipe data boolean, dimulai dari dua variabel boolean langsung (True), lalu membandingkan nilai numerik memakai operator perbandingan (>=) yang otomatis menghasilkan nilai boolean pada variabel status_kelulusan, dan diakhiri pernyataan if dengan operator logika and untuk mengecek dua kondisi sekaligus sebelum menampilkan pesan kelulusan.

1. Bagian 1 sampai 2 berfungsi untuk membuat variabel Boolean is_lulus_3018 dengan nilai True dan is_cumlaude_3018 dengan nilai True.
2. Bagian 3 sampai 4 berfungsi untuk menyimpan nilai mahasiswa dan batas nilai kelulusan ke dalam variabel.
3. Bagian 5 berfungsi untuk menentukan status_kelulusan_3018 
4. Bagian 6 sampai 8 berfungsi untuk menampilkan judul, nilai mahasiswa, dan hasil status kelulusan ke layar yang menggunakan operator logika if.

### 2.2.2 Program "Input_2611533018"

In [4]:
# Buat file dengan nama Input_NIM.py
# Buat program untuk menghitung luas persegi panjang
# Nama variabel ditambah 4 digit terakhir NIM contoh : a_3018
# Program ini menggunakan fungsi input() untuk meminta pengguna
# Masukkan nilai panjang dan lebar persegi panjang
# Nilai yang dimasukkan akan dikonversi mejadi data integer

panjang_3018 = input("Masukkan nilai panjang: ")
lebar_3018 = input("Masukkan nilai lebar: ")
luas_3018 = int(panjang_3018) * int(lebar_3018)
print("Luas = ", luas_3018)

Luas =  250


**Penjelasan :** Program ini menghitung luas persegi panjang dengan fungsi input() untuk menerima panjang dan lebar dari pengguna, di mana nilainya masih berupa string sehingga dikonversi ke integer dengan int() sebelum dikalikan, lalu hasilnya ditampilkan dengan print().

1. Bagian 1 sampai 2 berfungsi untuk meminta pengguna memasukkan nilai panjang dan lebar persegi panjang menggunakan fungsi input().
2. Bagian 3 berfungsi untuk mengubah nilai panjang dan lebar menjadi tipe data integer, kemudian menghitung luas persegi panjang.
3. Bagian 4 berfungsi untuk menampilkan hasil perhitungan luas persegi panjang ke layar.

### 2.2.3 Program "Konstanta_2611533018"

In [8]:
# Buat file dengan nama Konstanta_NIM.py
# Program ini menggunakan konstanta untuk menghitung luas lingkaran
# Nama variabel ditambah 4 digit terakhir NIM contoh : jari_3018

from typing import Final
PI: Final = 3.14
print("pi: %f" % (PI))
jari_3018 = float(input("Masukkan nilai jari-jari: "))
luas_3018 = PI * jari_3018 * jari_3018
print("Luas lingkaran dengan jari-jari %.2f adalah %.2f" % (jari_3018, luas_3018))

pi: 3.140000
Luas lingkaran dengan jari-jari 35.00 adalah 3846.50


**Penjelasan :** Program ini menghitung luas lingkaran menggunakan konstanta PI yang dideklarasikan dengan anotasi Final dari modul typing agar nilainya tidak bisa diubah, kemudian jari-jari diminta lewat input() dan dikonversi ke float, lalu hasilnya ditampilkan dengan format string (%f dan %.2f) agar angka desimalnya rapi.

1. Bagian 1 sampai 2 berfungsi untuk mengimpor Final dan menentukan nilai konstanta PI sebesar 3.14.
2. Bagian 3 sampai 4 berfungsi untuk menampilkan nilai PI dan meminta pengguna memasukkan nilai jari-jari lingkaran.
3. Bagian 5 berfungsi untuk menghitung luas lingkaran menggunakan nilai PI dan jari-jari yang telah dimasukkan.
4. Bagian 6 berfungsi untuk menampilkan hasil perhitungan luas lingkaran dengan format dua angka di belakang koma.

### 2.2.4 Program "Numerik_2611533018"

In [11]:
# buat file dengan nama Numerik_NIm.py
# Nama variabel ditambah 4 digit terakhir NIM contoh : a_3018
# create a variable with numeric type of value.
a_3018 = 100
print("The type of variable having value", a_3018, "is", type(a_3018))

#create a variable with float value
b_3018 = 10.2345
print("The type of variable having value", b_3018, "is", type(b_3018))

#create a variable with complex value.
c_3018 = 100+3j
print("The type of variable having value", c_3018, "is", type(c_3018))

The type of variable having value 100 is <class 'int'>
The type of variable having value 10.2345 is <class 'float'>
The type of variable having value (100+3j) is <class 'complex'>


**Penjelasan :** Program ini menunjukkan tiga jenis tipe data numerik Python — integer, float, dan complex — di mana tiap nilai disimpan dalam variabel lalu ditampilkan bersama tipe datanya menggunakan fungsi type() untuk membuktikan Python otomatis mengenali tipe data yang dipakai.

1. Bagian 1 sampai 2 berfungsi untuk membuat variabel a_3018 dengan nilai 100 dan menampilkan nilai serta tipe datanya menggunakan fungsi type(), yaitu type integer.
2. Bagian 3 sampai 4 berfungsi untuk membuat variabel b_3018 dengan nilai 10.2345 dan menampilkan nilai serta tipe datanya, yaitu type float.
3. Bagian 5 sampai 6 berfungsi untuk membuat variabel c_3018 dengan nilai kompleks 100+3j dan menampilkan nilai serta tipe datanya, yaitu type complex.

### 2.2.5 Program "String_2611533018"

In [12]:
# Buat file dengan nama String_NIM.py
# Nama variabel ditambah 4 digit terakhir NIM contoh : a_3018
# ganti programnya dan data masing masing
nama_3018 = "Raldo Restanggi Alfarizy"
jenis_kelamin_3018 = "Laki-laki"
alamat_3018 = """
    Kampus Unand
    Kec. Pauh
    Kota Padang
"""
agama_3018 = "Islam"
print("Nama saya adalah", nama_3018)
print("Jenis kelamin saya adalah", jenis_kelamin_3018)
print("Alamat saya adalah", alamat_3018)
print("Agama saya adalah", agama_3018)

Nama saya adalah Raldo Restanggi Alfarizy
Jenis kelamin saya adalah Laki-laki
Alamat saya adalah 
    Kampus Unand
    Kec. Pauh
    Kota Padang

Agama saya adalah Islam


**Penjelasan :** Program ini menampilkan data diri memakai tipe data string, termasuk string multi-baris yang diapit tiga tanda kutip (""" """) untuk menyimpan alamat yang terdiri dari beberapa baris, lalu tiap variabel ditampilkan dengan print() untuk menunjukkan bagaimana string dapat menyimpan dan menampilkan berbagai jenis informasi.

1. Bagian 1 sampai 2 berfungsi untuk membuat variabel nama_3018 dan jenis_kelamin_3018 yang menyimpan data nama dan jenis kelamin.
2. Bagian 3 sampai 7 berfungsi untuk membuat variabel alamat_3018 yang menyimpan data alamat dalam bentuk string yang terdiri dari beberapa baris.
3. Bagian 8 berfungsi untuk membuat variabel agama_3018 yang menyimpan data agama.
4. Bagian 9 sampai 12 berfungsi untuk menampilkan nama, jenis kelamin, alamat, dan agama ke layar menggunakan fungsi print().

---
# BAB III
# KESIMPULAN

Berdasarkan kegiatan praktikum yang telah dilakukan mengenai tipe data dan variabel pada bahasa pemrograman Python, dapat diperoleh beberapa kesimpulan sebagai berikut:

1. **Variabel dalam Python** dapat dideklarasikan secara langsung tanpa perlu menentukan tipe datanya terlebih dahulu, karena Python menggunakan sistem dynamic typing yang secara otomatis mengenali tipe data berdasarkan nilai yang diberikan.

2. **Tipe data Boolean** (True/False) berguna untuk merepresentasikan nilai logika dan dapat dikombinasikan dengan operator perbandingan serta operator logis (seperti and) untuk pengambilan keputusan, sebagaimana ditunjukkan pada program Boolean_2611533018.

3. **Fungsi input()** memungkinkan program menerima data secara interaktif dari pengguna, namun nilai yang dihasilkan selalu bertipe string sehingga perlu dikonversi (type casting) menggunakan int() atau float() sebelum digunakan dalam operasi matematis, seperti pada program Input_2611533018 dan Konstanta_2611533018.

4. **Konstanta** dapat dideklarasikan menggunakan anotasi Final dari modul typing agar nilainya tidak berubah selama program berjalan, seperti nilai PI pada program Konstanta_2611533018.

5. Python memiliki beberapa tipe data numerik, yaitu integer, float, dan complex, yang masing-masing dapat diidentifikasi secara otomatis menggunakan fungsi type(), sebagaimana ditunjukkan pada program Numerik_2611533018.

6. **Tipe data String** dapat digunakan untuk menyimpan dan menampilkan data teks, termasuk teks multi-baris menggunakan tanda kutip tiga (""" """), seperti pada program String_2611533018.

7. Melalui praktikum ini, pemahaman mengenai variabel, tipe data dasar, dan konversi tipe data menjadi lebih kuat sebagai bekal untuk mempelajari materi pemrograman Python yang lebih kompleks pada pertemuan berikutnya.

---
## DAFTAR PUSTAKA

[1]  ​Lubanovic, B. (2019). Introducing Python: Modern Computing in Simple Packages (2nd ed.). O'Reilly Media. Link: https://www.oreilly.com/library/view/introducing-python-2nd/9781492051374/

[2] ​Matthes, E. (2019). Python Crash Course: A Hands-On, Project-Based Introduction to Programming (2nd ed.). No Starch Press. Link: https://nostarch.com/pythoncrashcourse2e

[3] ​Severance, C. R. (2016). Python for Everybody: Exploring Data in Python 3. CreateSpace Independent Publishing Platform. Link: https://www.py4e.com/book

[4] ​Swaroop, C. H. (2013). A Byte of Python. Link: https://python.swaroopch.com/